# Use root/example as user/password credentials

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: application
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"